import type { NextPage } from 'next';
import Head from 'next/head';
import { GlitchedText } from '../components/GlitchedText';
import { Skills } from '../components/Skills';
import { TechUsed } from '../components/TechUsed';
import { Title } from '../components/Title';
import styles from '../styles/Home.module.scss';

const Home: NextPage = () => {
  return (
    <div className={styles.wrapper}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title />
        <Skills />
      </main>
    </div>
  );
};

export default Home;
